# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'pry'
Rails.application.load_tasks

task :build do
  `cd ../client && lineman build`
  `rm -rf ./public/css`
  `rm -rf ./public/js`
  `mv ../client/dist/* ./public`
  puts "You're good to go."
end